Better italian translations.
syberia-project/platform_packages_apps_SyberiaSettings pull request #21
Opened 2018-09-02 09:45 UTC by linjie997

I misunderstood some strings xP

2018-09-04 03:09 UTC, alexxxdev requested changes

2018-09-04 03:09 UTC, alexxxdev commented on res/values-it/string.xml
> +    <string name="double_tap_sleep_lockscreen_summary">Doppio tap in qualsiasi parte della schermata di blocco per spegnere lo schermo</string>
Also it is necessary to change in those places where there is a reference to this line 
(example lockscreen_settings.xml)

2018-09-04 07:00 UTC, linjie997 commented
The only one I found was in lockscreen_settings.xml
It has be done here https://github.com/syberia-project/platform_packages_apps_SyberiaSettings/pull/21/commits/1e125eece563b4f488fae0c88db846977d5fadda#diff-8b0f38b9d4b629668c5ab357f3b86ca4

2018-09-05 01:45 UTC, alexxxdev approved these changes

2018-09-05 01:45 UTC, merged